apiVersion: v1
kind: ReplicationController
metadata:
  name: luckwine-portal-web
  namespace: prod
spec:
  replicas: 1
  selector:
    app: luckwine-portal-web
  template:
    metadata:
      labels:
        app: luckwine-portal-web
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "www.abc.com"
      containers:
        - name: luckwine-portal-web
          image: luckwine-portal-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8030
          volumeMounts:
            - name: luckwine-volume
              mountPath: /data/applog
      volumes:
        - name: luckwine-volume
          hostPath:
            path: /data/docker/luckwine-portal-web