apiVersion: v1
kind: Service
metadata:
  name: luckwine-mysql
  namespace: prod
spec:
  ports:
    - name: luckwine-mysql
      port: 3306
      targetPort: 3306
      nodePort: 30021
      protocol: TCP
  selector:
    app: luckwine-mysql
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: luckwine-mysql
  namespace: prod
spec:
  selector:
    matchLabels:
      app: luckwine-mysql
  replicas: 1
  serviceName: luckwine-mysql
  template:
    metadata:
      labels:
        app: luckwine-mysql
    spec:
      containers:
        - name: luckwine-mysql
          image: luckwine-mysql:latest
          ports:
            - containerPort: 3306
              name: luckwine-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Aa123456"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          hostPath:
            path: /data/docker/luckwine-mysql/db
