server:
  port: 8030

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://luckwine-mysql:3306/luckwine-oss?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    # ·加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: Aa123456
  # Redis
  redis:
    host: luckwine-redis
  #Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: luckwine-elasticsearch:9300

oss:
  # ES
  elasticsearch:
    nodeClient: luckwine-elasticsearch:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: true

dubbo:
  registry:
    address: zookeeper://luckwine-zookeeper:2181
