# 配置文件加密key
jasypt:
  encryptor:
    password: howell

server:
  port: 9999

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/luckwine-oss?characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: Aa123456

  redis:
    host: 127.0.0.1
  #Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181