server:
  port: 8030

spring:
  # Redis
  redis:
    host: luckwine-redis
  #Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: luckwine-es:9300

portal:
  elasticsearch:
    nodeClient: luckwine-es:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: true

dubbo:
  protocol:
    port: 28038
  registry:
    address: zookeeper://luckwine-zk:2181
