server:
  port: 3333

spring:
  # Redis
  redis:
    host: 127.0.0.1
  #Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300

portal:
  # ES
  elasticsearch:
    nodeClient: 127.0.0.1:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: true

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
