
orderEnv: 0

server:
  port: 8030

jasypt:
  encryptor:
    password: luckwine_pgw

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://luckwine-mysql:3306/luckwine-pgw?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Aa123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: luckwine-redis


dubbo:
  registry:
    address: luckwine-zk:2181
  protocol:
    port: 28038
  provider:
    version: 1.0.0


alipay:
  appId:
  serverUrl:
  ## 应用私钥
  privateKey:
  ## 支付宝的公钥
  publicKey:
  charset: utf-8
  signType: RSA2
  format: json
  returnUrl:
  notifyUrl:
  timeoutExpress : 15m
