server:
  port: 8030

jasypt:
  encryptor:
    password: luckwine_goods

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://luckwine-mysql:3306/luckwine-goods?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Aa123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: luckwine-redis

  elasticsearch:
    rest:
      uris: http://luckwine-es:9200

dubbo:
  registry:
    address: zookeeper://luckwine-zk:2181
  protocol:
    port: 28038
  provider:
    version: 1.0.0
