apiVersion: v1
kind: Service
metadata:
  name: luckwine-portal-service
  namespace: prod
spec:
  ports:
    - name: luckwine-portal-service
      port: 8030
      targetPort: 8030
      nodePort: 30002
      protocol: TCP
  selector:
    app: luckwine-portal-service
  type: NodePort