apiVersion: v1
kind: Service
metadata:
  name: luckwine-portal-web
  namespace: prod
spec:
  ports:
    - name: luckwine-portal-web
      port: 8030
      targetPort: 8030
      nodePort: 30003
      protocol: TCP
  selector:
    app: luckwine-portal-web
  type: NodePort