apiVersion: v1
kind: Service
metadata:
  name: luckwine-oss-service
  namespace: prod
spec:
  ports:
    - name: luckwine-oss-service
      port: 8030
      targetPort: 8030
      nodePort: 30001
      protocol: TCP
  selector:
    app: luckwine-oss-service
  type: NodePort