server:
  port: 8030

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://luckwine-mysql:3306/luckwine-customer?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    # ·加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: Aa123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
  # Redis
  redis:
    host: luckwine-redis
    password:
    # 数据库索引 默认0
    database: 1
    port: 6379
    timeout: 3000



dubbo:
  protocol:
    port: 28038
  registry:
    address: zookeeper://luckwine-zk:2181


