version: '2'
services:
  luckwine-mysql:
    image: luckwine-mysql:latest
    container_name: luckwine-mysql
    restart: always
    volumes:
      - /data/docker/luckwine-db:/var/lib/mysql
    ports:
      - 3306:3306
  luckwine-redis:
    image: redis:latest
    container_name: luckwine-redis
    restart: always
    ports:
      - 6379
  luckwine-zk:
    image: zookeeper:latest
    container_name: luckwine-zk
    restart: always
    ports:
      - 2181:2181
      - 2888
      - 3888
  luckwine-elasticsearch:
    image: elasticsearch:6.4.0
    container_name: luckwine-elasticsearch
    restart: always
    environment:
      -  discovery.type=single-node
    ports:
      - 9200
      - 9300
  luckwine-acct:
    image: luckwine-acct:latest
    container_name: luckwine-acct
    environment:
      - JAVA_OPTIONS=-Duser.timezone=GMT+8 -Xms256m -Xmx256m -Dspring.profiles.active=prod
    depends_on:
      - luckwine-mysql
      - luckwine-zk
      - luckwine-redis
      - luckwine-elasticsearch
    volumes:
      - /data/docker/luckwine-acct:/data
    ports:
      - 28038
      - 8030
  luckwine-bgw:
    image: luckwine-bgw:latest
    container_name: luckwine-bgw
    restart: always
    environment:
      - JAVA_OPTIONS=-Duser.timezone=GMT+8 -Xms256m -Xmx256m -Dspring.profiles.active=prod
    depends_on:
      - luckwine-mysql
      - luckwine-zk
      - luckwine-redis
      - luckwine-elasticsearch
    volumes:
      - /data/docker/luckwine-bgw:/data
    ports:
      - 28038
      - 8030
  luckwine-customer:
    image: luckwine-customer:latest
    container_name: luckwine-customer
    restart: always
    environment:
      - JAVA_OPTIONS=-Duser.timezone=GMT+8 -Xms256m -Xmx256m -Dspring.profiles.active=prod
    depends_on:
      - luckwine-mysql
      - luckwine-zk
      - luckwine-redis
      - luckwine-elasticsearch
    volumes:
      - /data/docker/luckwine-customer:/data
    ports:
      - 28038
      - 8030
  luckwine-goods:
    image: luckwine-goods:latest
    container_name: luckwine-goods
    restart: always
    environment:
      - JAVA_OPTIONS=-Duser.timezone=GMT+8 -Xms256m -Xmx256m -Dspring.profiles.active=prod
    depends_on:
      - luckwine-mysql
      - luckwine-zk
      - luckwine-redis
      - luckwine-elasticsearch
    volumes:
      - /data/docker/luckwine-goods:/data
    ports:
      - 28038
      - 8030
  luckwine-marketing:
    image: luckwine-marketing:latest
    container_name: luckwine-marketing
    restart: always
    environment:
      - JAVA_OPTIONS=-Duser.timezone=GMT+8 -Xms256m -Xmx256m -Dspring.profiles.active=prod
    depends_on:
      - luckwine-mysql
      - luckwine-zk
      - luckwine-redis
      - luckwine-elasticsearch
    volumes:
      - /data/docker/luckwine-marketing:/data
    ports:
      - 28038
      - 8030
  luckwine-pgw:
    image: luckwine-pgw:latest
    container_name: luckwine-pgw
    restart: always
    environment:
      - JAVA_OPTIONS=-Duser.timezone=GMT+8 -Xms256m -Xmx256m -Dspring.profiles.active=prod
    depends_on:
      - luckwine-mysql
      - luckwine-zk
      - luckwine-redis
      - luckwine-elasticsearch
    volumes:
      - /data/docker/luckwine-pgw:/data
    ports:
      - 28038
      - 8030
  luckwine-synthesize:
    image: luckwine-synthesize:latest
    container_name: luckwine-synthesize
    restart: always
    environment:
      - JAVA_OPTIONS=-Duser.timezone=GMT+8 -Xms256m -Xmx256m -Dspring.profiles.active=prod
    depends_on:
      - luckwine-mysql
      - luckwine-zk
      - luckwine-redis
      - luckwine-elasticsearch
    volumes:
      - /data/docker/luckwine-synthesize:/data
    ports:
      - 28038
      - 8030
  luckwine-trade:
    image: luckwine-trade:latest
    container_name: luckwine-trade
    restart: always
    environment:
      - JAVA_OPTIONS=-Duser.timezone=GMT+8 -Xms256m -Xmx256m -Dspring.profiles.active=prod
    depends_on:
      - luckwine-mysql
      - luckwine-zk
      - luckwine-redis
      - luckwine-elasticsearch
    volumes:
      - /data/docker/luckwine-trade:/data
    ports:
      - 28038
      - 8030
  luckwine-oss-service:
    image: luckwine-oss-service:latest
    container_name: luckwine-oss-service
    restart: always
    environment:
      - JAVA_OPTIONS=-Duser.timezone=GMT+8 -Xms256m -Xmx256m -Dspring.profiles.active=prod
    depends_on:
      - luckwine-mysql
      - luckwine-zk
      - luckwine-redis
      - luckwine-elasticsearch
    volumes:
      - /data/docker/luckwine-oss-service:/data
    ports:
      - 8030
  luckwine-portal-service:
    image: luckwine-portal-service:latest
    container_name: luckwine-portal-service
    restart: always
    environment:
      - JAVA_OPTIONS=-Duser.timezone=GMT+8 -Xms256m -Xmx256m -Dspring.profiles.active=prod
    depends_on:
      - luckwine-mysql
      - luckwine-zk
      - luckwine-redis
      - luckwine-elasticsearch
    volumes:
      - /data/docker/luckwine-portal-service:/data
    ports:
      - 8030
  luckwine-oss-web:
    image: luckwine-oss-web:latest
    container_name: luckwine-oss-web
    restart: always
    depends_on:
      - luckwine-oss-service
    ports:
      - 8010:8030
  luckwine-portal-web:
    image: luckwine-portal-web:latest
    container_name: luckwine-portal-web
    restart: always
    depends_on:
      - luckwine-portal-service
    ports:
      - 8020:8030